### ISSUE TITLE
No longer able to download software

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/kids-ruby-quiz#7]
We received this email to info@raspberrypi.com

Your name Andrew LitmanYour email litmanandrew@gmail.comSubject Something elseYour message Could you please update or remove the "Kids Ruby Quiz" project? It is no longer possible to download the editor and I think it might be confusing to new users. Thank You. | Your name |   | Andrew Litman | Your email |   | litmanandrew@gmail.com | Subject |   | Something else | Your message |   | Could you please update or remove the "Kids Ruby Quiz" project? It is no longer possible to download the editor and I think it might be confusing to new users. Thank You.

-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Your name
  | Andrew Litman
Your email
  | litmanandrew@gmail.com
Subject
  | Something else
Your message
  | Could you please update or remove the "Kids Ruby Quiz" project? It is no longer possible to download the editor and I think it might be confusing to new users. Thank You.

**Comment by libxx1** [comment]
Delisted project as very old and no longer a priority for maintenance.
